spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: true
    #hibernate:
    #  ddl-auto: none
    #properties:
    #  hibernate:
    #    show_sql: true
    #    format_sql: true
  datasource:
    master:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:master;
      username: abc
      password: abc
      hikari:
        pool-name: master-pool
        maximum-pool-size: 5
    slave:
      driver-class-name: org.h2.Driver #org.mariadb.jdbc.Driver
      url: jdbc:h2:mem:slave; #jdbc:mariadb://localhost:3306/hello_batch
      username: abc
      password: abc
      hikari:
        pool-name: slave-pool
        maximum-pool-size: 5